### ISSUE TITLE
Update README with new onboarding instructions and ToS

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/w3up-client#84]
We want to update the README to give instructions on how to use the client in the different ways we expose. AFAIK, there are three main categories of integration:
- (Simplest) Client-server: Dev owns the Space and registers it with the service of their choosing, and their user uploads to your backend infra before uploading it to the service
- (More complex) Direct upload from client: Dev owns the Space and registers it with the service of their choosing, but gives a delegated UCAN token to their user to upload directly to the service
- (Most complex) User-owned: The end user owns the Space and registers it (likely with the service the dev chooses for them in your code, but not necessarily), and they use it to upload directly with the service (if the dev wants to instrument visibility into what they’re uploading, you’ll have to write separate code in your app for it)

To-dos:
- [x] Adjust ToS link at top of README (blocked on https://github.com/web3-storage/w3ui/issues/397)
- [x] Include below language to share link to ToS and note about registering with same email as your NFT.Storage / web3.storage account if you want them to get merged (#85)
- [x] Update https://github.com/web3-storage/w3up-client#creating-and-registering-spaces to reflect the latest recommended flow for registering with either NFT.Storage or web3.storage as a provider + accommodating for the possibility of logging in with an existing Account (to-do in #85)
- [x] Include docs for each of the three models above (#85)

> By registering your w3up beta Space via email confirmation with either [NFT.Storage](http://nft.storage/) or [web3.storage](http://web3.storage/), you agree to the relevant w3up beta Terms of Service (NFT.Storage, web3.storage include links). If you have an existing non-w3up beta account with NFT.Storage or web3.storage and register for the w3up beta version of the same product (NFT.Storage or web3.storage) using the same email, then at the end of the beta period, these accounts will be combined. Until the beta period is over and this migration occurs, uploads to w3up will not appear in your NFT.Storage or web3.storage account (and vice versa), even if you register with the same email.
